version: 0.2
env:
  variables:
    API_URL: 'https://api.joesworkouts.net/'
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete ./build "s3://www.joesworkouts.app"
artifacts:
  files: 
    - '**/*'
